package vSourabh.dataStructures.hashTable;

/**
 * @author Sourabh
 * 
 * LeetCode:
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s 
 * 	and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 *
 */
public class StringDifference {

	/**
	 * Input: s = "abcd" t = "abcde"
	 * Output: e
	 * Explanation: 'e' is the letter that was added.
	 */
	public char findTheDifference(String s, String t) {
		char c = 0;
		for (int i = 0; i < s.length(); ++i) 
			c ^= s.charAt(i);
		
		for (int i = 0; i < t.length(); ++i) 
			c ^= t.charAt(i);
		
		return c;
	}
	
	
	/**
	 * Input: s = "bcdefg" t = "bcdefgh"
	 * Output: h
	 * Explanation: 'h' is the letter that was added.
	 */
	public char findTheDifferenceBetterWay(String s, String t) {
		int n = t.length();
		char c = t.charAt(n - 1);
		for (int i = 0; i < n - 1; ++i) {
			c ^= s.charAt(i);
			c ^= t.charAt(i);
		}
		return c;
	}
	
	public static void main(String[] args) {
		StringDifference str = new StringDifference();
		char result = str.findTheDifference("abcd", "abcde");
		System.out.println("The different character is " + result);
		
		result = str.findTheDifferenceBetterWay("bcdefg", "bcdefgh");
		System.out.println("The different character in Better Way is " + result);
	}

}
